RabbitMq:
  Host: localhost
  Port: 5672
  Username: guest
  Password: guest

Stream:
  Loop: True
  Duration: 60
  Rate: 100
  Exchange: StreamExample
  From: Local
  Local:
    Source: StreamFolderExample
  S3:
    Url: Placeholder
    Bucket: Placeholder
  Redis:
    Url: Placeholder

Record:
  Duration: 60
  Exchange: RecordExample
  To: Local
  Local:
    Destination: RecordFolderExample
  S3:
    Url: Placeholder
    Bucket: Placeholder
  Redis:
    Url: Placeholder
